import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import TopNav from './_components/topNav';
import Sidebar from './_components/sidebar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sonzai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased main-bg`}
      >
        <TopNav />
        <div className="flex flex-row w-full items-center">
          <div className="sidebar-container">
            <Sidebar />
          </div>
          <div className="main-container">
            <main className="rounded-lg p-2">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
